# Generated by Django 5.2.1 on 2025-05-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('movie', 'Movie'), ('concert', 'Concert'), ('sports', 'Sports'), ('play', 'Play'), ('workshop', 'Workshop')], max_length=10)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('poster', models.ImageField(upload_to='posters/')),
            ],
        ),
    ]
