# Generated by Django 5.2.1 on 2025-05-26 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('venues', '0002_alter_seat_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('format', models.CharField(blank=True, max_length=20, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.screen')),
            ],
            options={
                'unique_together': {('screen', 'start_time')},
            },
        ),
    ]
